### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by gigisu20** [kennyvoo/CZ3002_Xeon#1]
the part of the complier problem down below
-------------------------------------------------------------------------------------------------------.
(library) PS C:\Users\kitty\Desktop\library\CZ3002_Xeon\Detection_System> python Detection.py
[ WARN:0] global C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-oduouqig\opencv\modules\videoio\src\cap_msmf.cpp (434) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
[ WARN:0] global C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-oduouqig\opencv\modules\videoio\src\cap_msmf.cpp (434) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
C:\Users\kitty\anaconda3\envs\library\lib\site-packages\google\cloud\firestore_v1\base_collection.py:295: UserWarning: Detected filter using positional arguments. Prefer using the 'filter' keyword argument instead.
  return query.where(field_path, op_string, value)
Traceback (most recent call last):
  File "Detection.py", line 208, in <module>
    main()
  File "Detection.py", line 77, in main
    im = imutils.resize(im1, width=416)
  File "C:\Users\kitty\anaconda3\envs\library\lib\site-packages\imutils\convenience.py", line 87, in resize
    r = width / float(w)
ZeroDivisionError: float division by zero

--------------------------------------------------------------------------------------------------------------------
Hello,I would like to ask you the problem down below .
Because I really want to successfully implement the system you wrote.
But there are some problems now.
I really need your help
Since no one around me can solve this problem, I have been researching it for two weeks now
hope you can help me soon.
---------------------------------------------------------------(i think the main problem )
   im = imutils.resize(im1, width=416)
  r = width / float(w)
ZeroDivisionError: float division by zero
--------------------------------------------------------------------------------

**Comment by kennyvoo** [comment]
Hi, @gigisu20 I'll try my best to help you. this is a very old project. I can help you to rewrite it if you want. this code is very messy.  
To debug your problem,
can you do the following checks to see 
1. if you can get frame from camera
```python
               
               cap = cv2.VideoCapture(CAMERA_IP[i])
               ret, frame = cap.read()
               if not ret:
                    raise(f'Error: failed to capture from {CAMERA_IP[i]}')

```
2.print the frame shape and the crop region 
```python
               ##Crop out seats images from the full picture
               for i in seatTemp:
                    print(frame.shape)
                    print(i["x1Img"],i["x2Img"],i["y1Img"],i["y2Img"])

```

**Comment by gigisu20** [comment]
Thank you so much for responding to my issue.
I am a college student and need to make such a project, so I am working very hard on this project.
So the two ways you gave
1.	if you can get frame from camera
2.	print the frame shape and the crop region

Both have been executed and checked, but the original problem still exists. I don’t know why it cannot be executed.

So I want to explain my situtation to you from the beginning.
On the operator (How to Run?)
1. cd SmartLib && npm run dev
2. cd Detection_System && python Detection.py

The first one(cd SmartLib && npm run dev) successfully connected and displayed the web page http://localhost:3000/
But the second one( python Detection.py) is the part where it currently stuck. When python Detection.py is executed, there will have the above questions I asked.
If possible, I wish you can help me to rewrite because I really cannot find the problem.
 I really really appreciate it.

Besides ,these two is the 「key point」 I want to execute successfully and display it.
1.How to launch your Admin Dashboard (able to view the live feed from the cameras and l show all the hogged seats)
2. and Modify Seat( able to modify (including delete) status, location and bounding box of every individual seat in the library)
In addition,I have a few things want to ask you
1. What kind of device are you connecting to CAMERA IP? Because I have connected WEBCAN (usb) but it can only connect to the screen shot of my computer itself.
2. Because I am not familiar with firebase, I don’t know how to connect. Can you write a step, such as which folder needs to be changed or a more detailed step
Sorry for asking you lots of questions,really appreciate for all your assistance.
